export const LIST_EDUCATION_REQUEST = "LIST_EDUCATION_REQUEST";
export const LIST_EDUCATION_SUCCESS = "LIST_EDUCATION_SUCCESS";
export const LIST_EDUCATION_FAILED = "LIST_EDUCATION_FAILED";

export const LIST_SUM_POP_REQUEST = "LIST_SUM_POP_REQUEST";
export const LIST_SUM_POP_SUCCESS = "LIST_SUM_POP_SUCCESS";
export const LIST_SUM_POP_FAILED = "LIST_SUM_POP_FAILED";

//population
export const LIST_POPULATIONS_REQUEST = "LIST_POPULATIONS_REQUEST";
export const LIST_POPULATIONS_SUCCESS = "LIST_POPULATIONS_SUCCESS";
export const LIST_POPULATIONS_FAILED = "LIST_POPULATIONS_FAILED";

export const LIST_POPULATIONS_MIDDLE_REQUEST =
  "LIST_POPULATIONS_MIDDLE_REQUEST";
export const LIST_POPULATIONS_MIDDLE_SUCCESS =
  "LIST_POPULATIONS_MIDDLE_SUCCESS";
export const LIST_POPULATIONS_MIDDLE_FAILED = "LIST_POPULATIONS_MIDDLE_FAILED";

export const LIST_POPULATIONS_AGE_REQUEST = "LIST_POPULATIONS_AGE_REQUEST";
export const LIST_POPULATIONS_AGE_SUCCESS = "LIST_POPULATIONS_AGE_SUCCESS";
export const LIST_POPULATIONS_AGE_FAILED = "LIST_POPULATIONS_AGE_FAILED";

export const LIST_POPULATIONS_TOTAL_REQUEST = "LIST_POPULATIONS_TOTAL_REQUEST";
export const LIST_POPULATIONS_TOTAL_SUCCESS = "LIST_POPULATIONS_TOTAL_SUCCESS";
export const LIST_POPULATIONS_TOTAL_FAILED = "LIST_POPULATIONS_TOTAL_FAILED";

export const LIST_TOTAL_AGE_REQUEST = "LIST_TOTAL_AGE_REQUEST";
export const LIST_TOTAL_AGE_SUCCESS = "LIST_TOTAL_AGE_SUCCESS";
export const LIST_TOTAL_AGE_FAILED = "LIST_TOTAL_AGE_FAILED";
